# Dimensionality Reduction

In [31]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.testing.compare import compare_images
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.manifold import TSNE
from sklearn.decomposition import TruncatedSVD
from scipy.spatial.distance import euclidean, cityblock
from IPython.display import HTML
from sklearn.decomposition import PCA

In [6]:
path = os.path.abspath(r'C:\Users\Armand\Documents\AIM_Documents\Courses\Term 3\DL\Session 2\UPCAT_DATA2.xlsx')
df = pd.read_excel(path).dropna()
df.tail()

,Batch,Eng7,Eng8,Eng9,Math7,Math8,Math9,Sci7,Sci8,Sci9,GWA7,GWA8,GWA9,UP,IQ,SA,C1,C2,Target
1005,2014,53,56.0,52,55,52,58.0,63,51,51,2.5577,2.6089,2.72984,1,26.0,23,1,5.0,0
1006,2014,59,67.0,57,71,61,64.0,67,63,67,2.4135,2.3589,2.32258,0,24.0,30,1,4.0,0
1007,2014,84,83.0,85,93,89,92.0,89,96,93,1.5192,1.4597,1.43952,0,86.0,72,1,4.0,1
1008,2014,78,83.0,77,82,62,69.0,84,71,70,1.7115,1.9556,2.02016,0,72.0,48,1,4.0,0
1009,2014,73,75.0,74,79,78,78.0,76,79,77,1.9231,1.7621,1.87500,1,68.0,48,1,4.0,1

# Principal Component Analysis (PCA)

In [54]:
from sklearn.decomposition import PCA

def pca_loadings(df, target, n):
    """
    Performs PCA and displays the loadings of features with the largest variance 
    explained with regards to a target variable. 
    
    Parameters
    ----------
    df : pandas dataframe
    
    target : str
        your dependent variable
        
    n : integer
        number of top loadings to display
    """
    dfx = df.drop(target, axis=1)
    X = np.array(dfx)
    pca = PCA(n_components=1)
    pca.fit(X)
    
    loadings = pd.DataFrame([({key: value for key,value in zip(dfx.columns, pca.components_[0])})],
             index=['weight']).transpose()
    loadings['abs_weight'] = np.abs(loadings['weight'])
    loadings.sort_values("abs_weight", ascending=False,inplace=True)
    top = loadings.head(n)
    return top

In [55]:
pca_loadings(df, 'Target', 10)

         weight  abs_weight
GWA8   0.998775    0.998775
SA    -0.027284    0.027284
IQ    -0.021774    0.021774
Math9 -0.016496    0.016496
Sci9  -0.014798    0.014798
Math8 -0.014224    0.014224
Math7 -0.012001    0.012001
Sci8  -0.010695    0.010695
Eng7  -0.010552    0.010552
Eng8  -0.010257    0.010257